import type { RestaurantSummary } from "./types";

/**
 * Mock data for development before the pipeline is wired up. These are real
 * Denver restaurants with approximate locations; scores and review counts are
 * fabricated. Replace with live Supabase queries once the pipeline produces data.
 */

// Ranks here approximate the production scoring (food_score weighted by volume,
// in the spirit of a Wilson-score-ish ordering). High % with low N is penalized
// against high % with high N — that's why Sap Sua (96% / 38 reviewers) sits
// behind Sushi Den (94% / 89 reviewers).
export const MOCK_DENVER_RESTAURANTS: RestaurantSummary[] = [
  {
    id: "mock-1",
    placeId: "mock-place-1",
    name: "Sushi Den",
    citySlug: "denver",
    neighborhood: "Platt Park",
    address: "1487 S Pearl St, Denver, CO",
    website: "https://sushiden.net",
    priceLevel: 4,
    location: [-104.9794, 39.6915],
    cuisines: ["japanese"],
    foodScore: 0.94,
    foodUniqueUsers: 89,
    serviceScore: 0.82,
    serviceUniqueUsers: 31,
    totalUniqueUsers: 92,
    tags: [],
    cityRank: 1,
  },
  {
    id: "mock-2",
    placeId: "mock-place-2",
    name: "Sap Sua",
    citySlug: "denver",
    neighborhood: "Congress Park",
    address: "2550 E Colfax Ave, Denver, CO",
    website: "https://sapsuadenver.com",
    priceLevel: 3,
    location: [-104.9551, 39.7402],
    cuisines: ["vietnamese", "american-fine-dining"],
    foodScore: 0.96,
    foodUniqueUsers: 38,
    serviceScore: 0.91,
    serviceUniqueUsers: 14,
    totalUniqueUsers: 41,
    tags: [],
    cityRank: 2,
  },
  {
    id: "mock-3",
    placeId: "mock-place-3",
    name: "Tacos Tequila Whiskey",
    citySlug: "denver",
    neighborhood: "Uptown",
    address: "1514 York St, Denver, CO",
    website: "https://tacostequilawhiskey.com",
    priceLevel: 2,
    location: [-104.9590, 39.7402],
    cuisines: ["mexican"],
    foodScore: 0.91,
    foodUniqueUsers: 47,
    serviceScore: 0.78,
    serviceUniqueUsers: 12,
    totalUniqueUsers: 51,
    tags: [],
    cityRank: 3,
  },
  {
    id: "mock-4",
    placeId: "mock-place-4",
    name: "Tavernetta",
    citySlug: "denver",
    neighborhood: "LoDo",
    address: "1889 16th St, Denver, CO",
    website: "https://tavernettadenver.com",
    priceLevel: 4,
    location: [-105.0010, 39.7530],
    cuisines: ["italian", "american-fine-dining"],
    foodScore: 0.89,
    foodUniqueUsers: 41,
    serviceScore: 0.86,
    serviceUniqueUsers: 18,
    totalUniqueUsers: 44,
    tags: [],
    cityRank: 4,
  },
  {
    id: "mock-5",
    placeId: "mock-place-5",
    name: "Hop Alley",
    citySlug: "denver",
    neighborhood: "RiNo",
    address: "3500 Larimer St, Denver, CO",
    website: "https://hopalleydenver.com",
    priceLevel: 3,
    location: [-104.9794, 39.7682],
    cuisines: ["chinese"],
    foodScore: 0.87,
    foodUniqueUsers: 56,
    serviceScore: 0.65,
    serviceUniqueUsers: 22,
    totalUniqueUsers: 60,
    tags: [],
    cityRank: 5,
  },
  {
    id: "mock-6",
    placeId: "mock-place-6",
    name: "Mister Oso",
    citySlug: "denver",
    neighborhood: "RiNo",
    address: "3163 Larimer St, Denver, CO",
    website: "https://misteroso.com",
    priceLevel: 3,
    location: [-104.9794, 39.7649],
    cuisines: ["mexican", "american-fine-dining"],
    foodScore: 0.88,
    foodUniqueUsers: 29,
    serviceScore: null,
    serviceUniqueUsers: 0,
    totalUniqueUsers: 29,
    tags: [],
    cityRank: 6,
  },
  {
    id: "mock-7",
    placeId: "mock-place-7",
    name: "Pizzeria Locale",
    citySlug: "denver",
    neighborhood: "Highlands",
    address: "3484 W 32nd Ave, Denver, CO",
    website: "https://pizzerialocale.com",
    priceLevel: 2,
    location: [-105.0309, 39.7625],
    cuisines: ["pizza", "italian"],
    foodScore: 0.83,
    foodUniqueUsers: 34,
    serviceScore: 0.72,
    serviceUniqueUsers: 9,
    totalUniqueUsers: 38,
    tags: [],
    cityRank: 7,
  },
  {
    id: "mock-8",
    placeId: "mock-place-8",
    name: "Safta",
    citySlug: "denver",
    neighborhood: "RiNo",
    address: "3330 Brighton Blvd, Denver, CO",
    website: "https://eatwithsafta.com",
    priceLevel: 3,
    location: [-104.9826, 39.7665],
    cuisines: ["middle-eastern"],
    foodScore: 0.85,
    foodUniqueUsers: 27,
    serviceScore: 0.71,
    serviceUniqueUsers: 11,
    totalUniqueUsers: 30,
    tags: [],
    cityRank: 8,
  },
  {
    id: "mock-9",
    placeId: "mock-place-9",
    name: "Snooze, an A.M. Eatery",
    citySlug: "denver",
    neighborhood: "Ballpark",
    address: "2262 Larimer St, Denver, CO",
    website: "https://snoozeeatery.com",
    priceLevel: 2,
    location: [-104.9890, 39.7553],
    cuisines: ["brunch-breakfast", "american-casual"],
    foodScore: 0.74,
    foodUniqueUsers: 73,
    serviceScore: 0.68,
    serviceUniqueUsers: 38,
    totalUniqueUsers: 81,
    tags: [],
    cityRank: 9,
  },
  {
    id: "mock-10",
    placeId: "mock-place-10",
    name: "Sam's No. 3",
    citySlug: "denver",
    neighborhood: "Downtown",
    address: "1500 Curtis St, Denver, CO",
    website: "https://samsno3.com",
    priceLevel: 1,
    location: [-104.9961, 39.7472],
    cuisines: ["american-casual", "brunch-breakfast"],
    foodScore: 0.66,
    foodUniqueUsers: 52,
    serviceScore: 0.59,
    serviceUniqueUsers: 24,
    totalUniqueUsers: 56,
    tags: [],
    cityRank: 10,
  },
];

export const MOCK_RESTAURANTS_BY_CITY: Record<string, RestaurantSummary[]> = {
  denver: MOCK_DENVER_RESTAURANTS,
  "new-orleans": [],
  calgary: [],
  paris: [],
};
